# Generated by Django 5.1.3 on 2024-11-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('src_ip', 'Source IP'), ('dst_ip', 'Destination IP'), ('src_port', 'Source Port'), ('dst_port', 'Destination Port'), ('flow_duration', 'Flow Duration'), ('tot_fwd_pkts', 'Total Forward Packets'), ('tot_bwd_pkts', 'Total Backward Packets'), ('flow_byts_per_sec', 'Flow Bytes Per Second'), ('flow_pkts_per_sec', 'Flow Packets Per Second'), ('fwd_iat_mean', 'Forward IAT Mean'), ('bwd_iat_mean', 'Backward IAT Mean'), ('protocol', 'Protocol'), ('down_up_ratio', 'Down-Up Ratio'), ('pkt_size_avg', 'Packet Size Average'), ('fwd_pkts_per_sec', 'Forward Packets Per Second'), ('bwd_pkts_per_sec', 'Backward Packets Per Second')], max_length=50, unique=True)),
                ('weight', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
