# Generated by Django 5.1.3 on 2024-11-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.PositiveIntegerField()),
                ('dst_port', models.PositiveIntegerField()),
                ('protocol', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('flow_duration', models.BigIntegerField()),
                ('tot_fwd_pkts', models.PositiveIntegerField()),
                ('tot_bwd_pkts', models.PositiveIntegerField()),
                ('flow_byts_per_sec', models.FloatField()),
                ('flow_pkts_per_sec', models.FloatField()),
                ('fwd_iat_mean', models.FloatField()),
                ('bwd_iat_mean', models.FloatField()),
                ('down_up_ratio', models.FloatField()),
                ('pkt_size_avg', models.FloatField()),
                ('fwd_pkts_per_sec', models.FloatField()),
                ('bwd_pkts_per_sec', models.FloatField()),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('data_type', models.CharField(choices=[('train', 'Training'), ('test', 'Testing'), ('unlabeled', 'Unlabeled')], db_index=True, default='unlabeled', max_length=10)),
            ],
            options={
                'db_table': 'download_db',
                'indexes': [models.Index(fields=['timestamp'], name='download_db_timesta_fd4b1e_idx'), models.Index(fields=['label'], name='download_db_label_4808dd_idx'), models.Index(fields=['data_type'], name='download_db_data_ty_75fdae_idx'), models.Index(fields=['src_ip'], name='download_db_src_ip_93b186_idx'), models.Index(fields=['dst_ip'], name='download_db_dst_ip_bf7b2e_idx')],
            },
        ),
    ]
