# Generated by Django 5.1.3 on 2024-11-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_download_db_ack_flag_cnt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download_db',
            old_name='custom_id',
            new_name='id',
        ),
    ]
